[package]
name = "mdarray-linalg-prototype"
version = "0.1.0"
edition = "2024"

[dependencies]
cblas-sys = "0.2.0"
mdarray = "0.7.0"

[dev-dependencies]
openblas-src = { version = "0.10.11", features = ["system"] }
