[package]
name = "mdarray-linalg-naive"
version = "0.1.0"
edition = "2024"

[dependencies]
mdarray-linalg = { version = "0.1.0", path = "../mdarray-linalg" }
mdarray = "0.7.1"
num-complex = "0.4.6"
num-traits = "0.2.19"
